#! python


def build(ctx):
    ctx(
        features="run_py_script", source="cross_validation.py", name="cross_validation",
    )

    ctx(
        features="run_py_script",
        source="test_cross_validation.py",
        deps=[ctx.path_to(ctx, "FUNCTIONS_NONPARAMETRIC", "cross_validation.py")],
        name="test_cross_validation",
    )

    ctx(features="run_py_script", source="rule_of_thumb.py", name="rule_of_thumb")

    ctx(
        features="run_py_script",
        source="test_rule_of_thumb.py",
        deps=[ctx.path_to(ctx, "FUNCTIONS_NONPARAMETRIC", "rule_of_thumb.py")],
        name="test_rule_of_thumb",
    )

    ctx(
        features="run_py_script",
        source="treatment_effect_estimation.py",
        name="treatment_effect_estimation",
    )

    ctx(
        features="run_py_script",
        source="test_treatment_effect_estimation.py",
        deps=[
            ctx.path_to(
                ctx, "FUNCTIONS_NONPARAMETRIC", "treatment_effect_estimation.py"
            )
        ],
        name="test_treatment_effect_estimation",
    )
