#! python


def build(ctx):
    ctx(
        features="run_py_script",
        source="treatment_effect_estimation.py",
        name="treatment_effect_estimation",
    )
    ctx(
        features="run_py_script",
        source="test_treatment_effect_estimation.py",
        deps=[
            ctx.path_to(ctx, "FUNCTIONS_PARAMETRIC", "treatment_effect_estimation.py")
        ],
        name="test_treatment_effect_estimation",
    )
