#! python


def build(ctx):
    ctx(
        features="run_py_script",
        source="local_polynomial.py",
        deps=[ctx.path_to(ctx, "FUNCTIONS", "test_local_polynomial.py")],
        name="local_polynomial",
    )
