#! python


def build(ctx):
    ctx(
        features="run_py_script", source="local_polynomial.py", name="local_polynomial",
    )

    ctx(
        features="run_py_script",
        source="test_local_polynomial.py",
        deps=[ctx.path_to(ctx, "FUNCTIONS", "local_polynomial.py")],
        name="test_local_polynomial",
    )

    ctx(
        features="run_py_script",
        source="cross_validation.py",
        deps=[ctx.path_to(ctx, "FUNCTIONS", "local_polynomial.py")],
        name="cross_validation",
    )

    ctx(
        features="run_py_script",
        source="test_cross_validation.py",
        deps=[ctx.path_to(ctx, "FUNCTIONS", "cross_validation.py")],
        name="test_cross_validation",
    )

    ctx(features="run_py_script", source="rule_of_thumb.py", name="rule_of_thumb")
