#! python


def build(ctx):
    ctx(
        features="run_py_script",
        source="reproduce_main_results.py",
        deps=[
            ctx.path_to(ctx, "IN_DATA", "Data_public_small.dta"),
            ctx.path_to(ctx, "FUNCTIONS_PARAMETRIC", "treatment_effect_estimation.py"),
            ctx.path_to(
                ctx, "FUNCTIONS_NONPARAMETRIC", "treatment_effect_estimation.py"
            ),
            ctx.path_to(ctx, "FUNCTIONS_NONPARAMETRIC", "rule_of_thumb.py"),
            ctx.path_to(ctx, "FUNCTIONS_NONPARAMETRIC", "cross_validation.py"),
        ],
        name="reproduce_main_results",
        target=[
            ctx.path_to(
                ctx,
                "OUT_TABLES",
                "data_analysis",
                "reproduce_main_results_table_2.tex",
            ),
            ctx.path_to(ctx, "OUT_TABLES", "data_analysis", "plot_results_ned.dta"),
            ctx.path_to(ctx, "OUT_TABLES", "data_analysis", "plot_results_wg_c.dta"),
        ],
    )

    ctx(
        features="run_py_script",
        source="reproduce_rdd_graphs.py",
        deps=[ctx.path_to(ctx, "IN_DATA", "Data_public_small.dta")],
        name="reproduce_rdd_graphs",
        target=[ctx.path_to(ctx, "OUT_FIGURES", "data_analysis", "rdd_graphs.png")],
    )

    ctx(
        features="run_py_script",
        source="treatment_effect_estimate_plot.py",
        deps=[
            ctx.path_to(ctx, "DATA_ANALYSIS", "reproduce_main_results.py"),
            ctx.path_to(ctx, "OUT_TABLES", "data_analysis", "plot_results_ned.dta"),
            ctx.path_to(ctx, "OUT_TABLES", "data_analysis", "plot_results_wg_c.dta"),
        ],
        name="treatment_effect_estimate_plot",
        target=[
            ctx.path_to(
                ctx, "OUT_FIGURES", "data_analysis", "treatment_effect_estimates.png",
            ),
        ],
    )
